
SET IDENTITY_INSERT dbo.ProductDetails ON

INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-2','Network','HSPA 21.1/5.76 Mbps, LTE Cat4 150/50 Mbps',501,502);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-2','Display','6.6 inches, 105.2 cm2 (~83.2% screen-to-Body ratio)',502,502);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-2','Platform','Android 10 (Go edition)',503,502);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-2','Body','165.4 x 76.4 x 8.8 mm',504,502);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-2','Memory','microSDXC (dedicated slot)',505,502);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-2','Main Camera','8 MP + QVGA',506,502);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-2','Selfie Camera','Dual-LED flash',507,502);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-2','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',508,502);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-2','Features','Fingerprint (rear-mounted), accelerometer, gyro, proximity',509,502);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-2','Battery','Li-Po 5000 mAh, non-removable',510,502);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-1','Network','GSM / HSPA / LTE',511,501);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-1','Display','IPS LCD',512,501);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-1','Platform','Android 11 realme UI',513,501);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-1','Body','165.2 × 76.4 × 8.9 mm',514,501);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-1','Memory','microSDXC (dedicated slot)',515,501);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-1','Main Camera','16 MP + QVGA',516,501);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-1','Selfie Camera','Dual-LED flash',517,501);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-1','Communications','Wi-Fi 751.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',518,501);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-1','Battery','Li-Po 5000 mAh, non-removable',519,501);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-3','Network','HSDPA 850 / 900 / 2100',520,503);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-3','Display','720 x 1600 pixels, 20:9 ratio (~264 ppi density)',521,503);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-3','Platform','Android 10',522,503);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-3','Body','164 x 75.8 x 8.9 mm',523,503);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-3','Memory','microSDXC (dedicated slot)',524,503);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-3','Main Camera','48 MP, f/2.0, 26mm (wide), AF',525,503);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-3','Selfie Camera','8 MP, f/2.2',526,503);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-3','Communications','Wi-Fi 802.11 b/g/n, Wi-Fi Direct, hotspot',527,503);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-3','Battery','Li-Po 5000 mAh, non-removable',528,503);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-4','Network','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2',529,504);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-4','Display','6.5 inches, 102.0 cm2 (~83.4% screen-to-body ratio)',530,504);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-4','Platform','Android 11, MIUI 12.5',531,504);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-4','Body','162 x 75.5 x 8.9 mm',532,504);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-4','Memory','128GB 4GB RAM',533,504);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-4','Main Camera','50 MP, f/1.8, (wide), PDAF',534,504);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-4','Selfie Camera','8 MP, f/2.0, (wide)',535,504);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-4','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',536,504);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-4','Battery','Li-Po 5000 mAh, non-removable',537,504);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-5','Network','GSM 850 / 900 / 1800 / 1900',538,505);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-5','Display','6.5 inches, 106.7 cm2 (~85.8% screen-to-Body ratio)',539,505);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-5','Platform','Android 10',540,505);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-5','Body','164 x 75.8 x 8.9 mm',541,505);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-5','Memory','128GB 4GB RAM',542,505);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-5','Main Camera','48 MP, f/2.0, 26mm (wide), AF',543,505);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-5','Selfie Camera','8 MP, f/2.2',544,505);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-5','Communications','Wi-Fi 802.11 b/g/n, Wi-Fi Direct, hotspot',545,505);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-5','Battery','Li-Po 5000 mAh, non-removable',546,505);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-6','Network','HSPA 21.1/5.76 Mbps, LTE Cat4 150/50 Mbps',547,506);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-6','Display','6.6 inches, 105.2 cm2 (~83.2% screen-to-Body ratio)',548,506);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-6','Platform','Android 10 (Go edition)',549,506);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-6','Body','165.4 x 76.4 x 8.8 mm',550,506);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-6','Memory','microSDXC (dedicated slot)',551,506);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-6','Main Camera','8 MP + QVGA',552,506);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-6','Selfie Camera','Dual-LED flash',553,506);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-6','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',554,506);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-6','Features','Fingerprint (rear-mounted), accelerometer, gyro, proximity',555,506);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-6','Battery','Li-Po 5000 mAh, non-removable',556,506);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-7','Network','HSDPA 850 / 900 / 1900 / 2100',557,507);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-7','Display','IPS LCD capacitive touchscreen, 16M colors',558,507);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-7','Platform','Android 9.0 (Pie)',559,507);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-7','Body','164.9 x 75.8 x 8.4 mm',560,507);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-7','Memory','128GB ROM, 6GB RAM',561,507);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-7','Main Camera','16 MP, f/1.8, 27mm (wide), 1/2.8", 1.12µm, PDAF',562,507);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-7','Selfie Camera','8 MP, f/2.0, 25mm (wide), 1/4", 1.12µm',563,507);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-7','Communications','Wi-Fi 802.11 b/g/n, Wi-Fi Direct, hotspot',564,507);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-7','Features','Fingerprint (rear-mounted), accelerometer, proximity',565,507);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-7','Battery','Battery charging 10W',566,507);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-8','Network','HSDPA 850 / 900 / 2100',567,508);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-8','Display','720 x 1600 pixels, 20:9 ratio (~264 ppi density)',568,508);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-8','Platform','Android 10',569,508);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-8','Body','164 x 75.8 x 8.9 mm',570,508);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-8','Memory','microSDXC (dedicated slot)',571,508);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-8','Main Camera','48 MP, f/2.0, 26mm (wide), AF',572,508);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-8','Selfie Camera','8 MP, f/2.2',573,508);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-8','Communications','Wi-Fi 802.11 b/g/n, Wi-Fi Direct, hotspot',574,508);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-8','Battery','Li-Po 5000 mAh, non-removable',575,508);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-9','Network','HSPA 42.2/5.76 Mbps, LTE-A',576,509);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-9','Display','6.43 inches, 99.8 cm2 (~83.5% screen-to-body ratio)',577,509);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-9','Platform','Android 11, MIUI 12.5',578,509);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-9','Body','160.5 x 74.5 x 8.3 mm',579,509);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-9','Memory','128GB 8GB RAM',580,509);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-9','Main Camera','64 MP, f/1.8, 26mm (wide), 1/1.97", 0.7µm, PDAF',581,509);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-9','Selfie Camera','13 MP, f/2.5, (wide), 1/3.06", 1.12µm',582,509);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-9','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',583,509);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-9','Battery','Li-Po 5000 mAh, non-removabl',584,509);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-10','Network','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2',585,510);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-10','Display','6.5 inches, 102.0 cm2 (~83.4% screen-to-body ratio)',586,510);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-10','Platform','Android 11, MIUI 12.5',587,510);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-10','Body','162 x 75.5 x 8.9 mm',588,510);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-10','Memory','128GB 4GB RAM',589,510);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-10','Main Camera','50 MP, f/1.8, (wide), PDAF',590,510);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-10','Selfie Camera','8 MP, f/2.0, (wide)',591,510);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-10','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',592,510);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-11','Network','HSPA 42.2/5.76 Mbps, LTE-A (CA) Cat18 1200/150 Mbps, 5G',593,511);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-11','Display','6.5 inches, 102.0 cm2 (~84.9% screen-to-body ratio)',594,511);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-11','Platform','Android 11, One UI 3.1',595,511);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-11','Body','159.9 x 75.1 x 8.4 mm',596,511);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-11','Memory','128GB, 8GB RAM',597,511);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-11','Main Camera','64 MP, f/1.8, 26mm (wide), 1/1.7", 0.8µm, PDAF, OIS',598,511);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-11','Selfie Camera','32 MP, f/2.2, 26mm (wide), 1/2.8", 0.8µm',599,511);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-11','Communications','Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot',600,511);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-12','Network','GSM 850 / 900 / 1800 / 1900',601,512);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-12','Display','6.5 inches, 106.7 cm2 (~85.8% screen-to-Body ratio)',602,512);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-12','Platform','Android 10',603,512);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-12','Body','164 x 75.8 x 8.9 mm',604,512);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-12','Memory','128GB 4GB RAM',605,512);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-12','Main Camera','48 MP, f/2.0, 26mm (wide), AF',606,512);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-12','Selfie Camera','8 MP, f/2.2',607,512);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-12','Communications','Wi-Fi 802.11 b/g/n, Wi-Fi Direct, hotspot',608,512);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-12','Battery','Li-Po 5000 mAh, non-removable',609,512);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-13','Network','GSM / HSPA / LTE',610,513);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-13','Display','163.8 x 75.6 x 8.4 mm',611,513);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-13','Platform','OS Android 11',612,513);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-13','Body','163.8 x 75.6 x 8.4 mm (6.45 x 2.98 x 0.33 in)',613,513);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-13','Memory','Card slot microSDXC',614,513);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-13','Main Camera','13 MP, f/2.2, 26mm (wide), 1/3.06", 1.12µm, PDAF',615,513);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-13','Selfie Camera','Single 8 MP, f/2.0, (wide)',616,513);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-13','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',617,513);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-13','Battery','Li-Po 5000 mAh, non-removable',618,513);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-14','Network','HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100',619,514);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-14','Display','1284 x 2778 pixels, 19.5:9 ratio (~458 ppi density)',620,514);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-14','Platform','iOS 15',621,514);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-14','Body','160.8 x 78.1 x 7.7 mm',622,514);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-14','Memory','256GB 6GB RAM',623,514);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-14','Main Camera','12 MP, f/1.5, 26mm (wide), 1.9µm, dual pixel PDAF, sensor-shift OIS',624,514);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-14','Selfie Camera','12 MP, f/2.2, 23mm (wide), 1/3.6',625,514);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-14','Communications','Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot',626,514);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-14','Battery','Li-Ion 4373 mAh, non-removable (16.75 Wh',627,514);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-15','Network','HSPA 21.1/5.76 Mbps, LTE Cat4 150/50 Mbps',628,515);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-15','Display','6.6 inches, 105.2 cm2 (~83.2% screen-to-Body ratio)',629,515);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-15','Platform','Android 10 (Go edition)',630,515);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-15','Body','165.4 x 76.4 x 8.8 mm',631,515);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-15','Memory','microSDXC (dedicated slot)',632,515);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-15','Main Camera','8 MP + QVGA',633,515);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-15','Selfie Camera','Dual-LED flash',634,515);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-15','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',635,515);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-15','Features','Fingerprint (rear-mounted), accelerometer, gyro, proximity',636,515);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-15','Battery','Li-Po 5000 mAh, non-removable',637,515);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-16','Network','HSDPA 850 / 900 / 2100',638,516);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-16','Display','720 x 1600 pixels, 20:9 ratio (~264 ppi density)',639,516);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-16','Platform','Android 10',640,516);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-16','Body','164 x 75.8 x 8.9 mm',641,516);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-16','Memory','microSDXC (dedicated slot)',642,516);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-16','Main Camera','48 MP, f/2.0, 26mm (wide), AF',643,516);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-16','Selfie Camera','8 MP, f/2.2',644,516);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-16','Communications','Wi-Fi 802.11 b/g/n, Wi-Fi Direct, hotspot',645,516);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-16','Battery','Li-Po 5000 mAh, non-removable',646,516);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-17','Network','HSPA 42.2/5.76 Mbps, LTE-A',647,517);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-17','Display','6.43 inches, 99.8 cm2 (~83.5% screen-to-body ratio)',648,517);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-17','Platform','Android 11, MIUI 12.5',649,517);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-17','Body','160.5 x 74.5 x 8.3 mm',650,517);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-17','Memory','128GB 8GB RAM',651,517);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-17','Main Camera','64 MP, f/1.8, 26mm (wide), 1/1.97", 0.7µm, PDAF',652,517);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-17','Selfie Camera','13 MP, f/2.5, (wide), 1/3.06", 1.12µm',653,517);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-17','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',654,517);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-17','Battery','Li-Po 5000 mAh, non-removabl',655,517);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-18','Network','GSM 850/900/1800/1900',656,518);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-18','Display','6.43 inches, 99.8 cm2 (~83.5% screen-to-body ratio)',657,518);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-18','Platform','OS Android 11',658,518);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-18','Body','164 x 75.8 x 8.9 mm',659,518);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-18','Memory','256GB 6GB RAM',660,518);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-18','Main Camera','8 MP + QVGA',661,518);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-18','Selfie Camera','Dual-LED flash',662,518);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-18','Communications','COMMS WLAN Wi-Fi 802.11 a / b / g / n / ac',663,518);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-18','Battery','Li-Ion 4373 mAh, non-removable (16.75 Wh',664,518);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-19','Network','HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100',665,519);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-19','Display','1284 x 2778 pixels, 19.5:9 ratio (~458 ppi density)',666,519);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-19','Platform','iOS 15',667,519);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-19','Body','160.8 x 78.1 x 7.7 mm',668,519);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-19','Memory','132GB 6GB RAM',669,519);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-19','Main Camera','12 MP, f/1.5, 26mm (wide), 1.9µm, dual pixel PDAF, sensor-shift OIS',670,519);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-19','Selfie Camera','12 MP, f/2.2, 23mm (wide), 1/3.6',671,519);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-19','Communications','Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot',672,519);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-19','Battery','Li-Ion 4373 mAh, non-removable (16.75 Wh',673,519);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-20','Network','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2',674,520);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-20','Display','6.5 inches, 102.0 cm2 (~83.4% screen-to-body ratio)',675,520);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-20','Platform','Android 11, MIUI 12.5',676,520);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-20','Body','162 x 75.5 x 8.9 mm',677,520);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-20','Memory','128GB 4GB RAM',678,520);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-20','Main Camera','50 MP, f/1.8, (wide), PDAF',679,520);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-20','Selfie Camera','8 MP, f/2.0, (wide)',680,520);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-20','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',681,520);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-21','Processor','Intel® Core™ i3-1005G1 Processor 1.20 GHz (4M Smart Cache, up to 3.40 GHz, # of Cores: 2)',682,521);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-21','Memory','4 GB DDR4-2666 MHz RAM (1 x 4 GB)',683,521);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-21','Display','15.6" diagonal, HD (1366 x 768), narrow bezel, anti-glare, 250 nits, 45% NTSC',684,521);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-21','Graphics','Intel® UHD Graphics',685,521);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-21','Storage','Internal drive: 1 TB 5400 rpm SATA HDD',686,521);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-21','I/O Ports','2 Super Speed USB Type-A 5Gbps signaling rate',687,521);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-21','Expansion slots','1 multi-format digital media reader',688,521);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-21','Hardware','Audio: Stereo speakers, integrated digital microphone',689,521);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-22','Processor','Intel Core i3-1005G1 (2C / 4T, 1.2 / 3.4GHz, 4MB)',690,522);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-22','Memory','4GB Soldered DDR4-2666',691,522);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-22','Display','15.6" FHD (1920x1080) TN 220nits Anti-glare',692,522);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-22','Graphics','Integrated Intel UHD Graphics',693,522);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-22','Storage','1TB HDD 5400rpm 2.5',694,522);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-22','I/O Ports','FreeDOS',695,522);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-22','Card Reader','4-in-1 Card Reader',696,522);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-22','WLAN + Bluetooth','11ac, 1x1 + BT4.2',697,522);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-23','Processor','11th Generation Intel® Core™ i5-1135G7 Processor (8MB Cache, 2.40 GHz up to 4.2 GHz),4 cores , 8 threads',698,523);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-23','Memory','8GB DDR4, 3200MHz',699,523);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-23','Display','15.6-inch HD (1366 x 768) Anti-glare LED Backlight Non-Touch Narrow Border WVA Display',700,523);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-23','Graphics','NVIDIA® GeForce® MX330 with 2GB GDDR5 graphics memory',701,523);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-23','Storage','1TB 5400 rpm Hard Drive',702,523);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-23','I/O Ports','3-in-1 SD Media Card',703,523);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-23','Card Reader','USB 3.2 Gen 1 Type-C™ (Data only)',704,523);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-23','WLAN + Bluetooth','802.11ac 1x1 WiFi and Bluetooth',705,523);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-24','Processor','AMD Ryzen 3 3300U Mobile Processor, 2.10 GHz',706,524);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-24','Memory','4GBMemory Type: DDR4 2400MHz',707,524);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-24','Display','Screen Size: 14-inchResolution: HD (1366 x 768)',708,524);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-24','Graphics','Graphics Processor: Integrated AMD Radeon Vega 6 GraphicsGraphics Video RAM: Shared',709,524);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-24','Storage','1TBStorage Technology: 5400rpm',710,524);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-24','I/O Ports','2 USB 3.1 Gen 1',711,524);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-24','Card Reader','AC power1 multi-format digital media reader',712,524);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-24','WLAN + Bluetooth','Wi-Fi 802.11 acBluetooth® 4.2',713,524);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-25','Processor','Intel® Core™ i3-1005G1 Processor 1.20 GHz (4M Smart Cache, up to 3.40 GHz, # of Cores: 2)',714,525);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-25','Memory','4 GB DDR4-2666 MHz RAM (1 x 4 GB)',715,525);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-25','Display','15.6" diagonal, HD (1366 x 768), narrow bezel, anti-glare, 250 nits, 45% NTSC',716,525);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-25','Graphics','Intel® UHD Graphics',717,525);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-25','Storage','Internal drive: 1 TB 5400 rpm SATA HDD',718,525);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-25','I/O Ports','2 Super Speed USB Type-A 5Gbps signaling rate',719,525);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-25','Expansion slots','1 multi-format digital media reader',720,525);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-25','Hardware','Audio: Stereo speakers, integrated digital microphone',721,525);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-26','Processor','Intel Core i3-1005G1 (2C / 4T, 1.2 / 3.4GHz, 4MB)',722,526);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-26','Memory','4GB Soldered DDR4-2666',723,526);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-26','Display','15.6" FHD (1920x1080) TN 220nits Anti-glare',724,526);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-26','Graphics','Integrated Intel UHD Graphics',725,526);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-26','Storage','1TB HDD 5400rpm 2.5',726,526);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-26','I/O Ports','FreeDOS',727,526);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-26','Card Reader','4-in-1 Card Reader',728,526);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-26','WLAN + Bluetooth','11ac, 1x1 + BT4.2',729,526);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-27','Processor','Intel® Core™ i3-10110U Processor, 2.10 GHz (4M Cache, Max Turbo Frequency up to 4.10 GHz, # of Cores: 2)',730,527);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-27','Memory','Installed Memory: 4 GB RAM',731,527);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-27','Display','Screen Size: 15.6-inch',732,527);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-27','Graphics','NVIDIA GeForce MX130 2GB GDDR5',733,527);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-27','Storage','Storage Capacity: 1TB SATA HDD',734,527);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-27','I/O Ports','2 x USB-A 3.1 Gen 1',735,527);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-27','Card Reader','Camera: 0.3MP Fixed Focus camera with Dual Microphone',736,527);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-27','WLAN + Bluetooth','Wi-Fi 802.11 b/g/n/ac 2x2',737,527);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-28','Processor','AMD Ryzen 3 3300U Mobile Processor, 2.10 GHz',738,528);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-28','Memory','4GBMemory Type: DDR4 2400MHz',739,528);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-28','Display','Screen Size: 14-inchResolution: HD (1366 x 768)',740,528);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-28','Graphics','Graphics Processor: Integrated AMD Radeon Vega 6 GraphicsGraphics Video RAM: Shared',741,528);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-28','Storage','1TBStorage Technology: 5400rpm',742,528);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-28','I/O Ports','2 USB 3.1 Gen 1',743,528);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-28','Card Reader','AC power1 multi-format digital media reader',744,528);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-28','WLAN + Bluetooth','Wi-Fi 802.11 acBluetooth® 4.2',745,528);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-29','Processor','Intel® Core™ i3-1005G1 Processor 1.20 GHz (4M Smart Cache, up to 3.40 GHz, # of Cores: 2)',746,529);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-29','Memory','4 GB DDR4-2666 MHz RAM (1 x 4 GB)',747,529);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-29','Display','15.6" diagonal, HD (1366 x 768), narrow bezel, anti-glare, 250 nits, 45% NTSC',748,529);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-29','Graphics','Intel® UHD Graphics',749,529);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-29','Storage','Internal drive: 1 TB 5400 rpm SATA HDD',750,529);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-29','I/O Ports','2 Super Speed USB Type-A 5Gbps signaling rate',751,529);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-29','Expansion slots','1 multi-format digital media reader',752,529);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-29','Hardware','Audio: Stereo speakers, integrated digital microphone',753,529);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-30','Processor','Intel® Core ™ i3-1115G4 3.0',754,530);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-30','Memory','4GBMemory Type: DDR4 2400MHz',755,530);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-30','Display','Screen Size: 14-inchResolution: HD (1366 x 768)',756,530);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-30','Graphics','Integrated Intel UHD Graphics',757,530);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-30','Storage','1TB HDD 5400rpm 2.5',758,530);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-30','I/O Ports','3 USB 3.1 Gen 1',759,530);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-30','Expansion slots','1 multi-format digital media reader',760,530);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-31','Processor','11th Gen Intel Core i7 - 11370H - Speed: 3.3 GHz (Base) - 4.8 GHz (Max) - 4 Cores - 8 Threads - 12MB Cache',761,531);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-31','Memory','8GB RAM DDR4-3200',762,531);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-31','Storage','256GB SSD + 1TB hdd',763,531);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-31','Display','15.6" FHD (1920x1080) - IPS Technology - 120 Hz Refresh Rate - 250Nits Brightness',764,531);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-31','Graphics','NVIDIA GeForce RTX 3050 4GB GDDR6 Dedicated Graphics with max TGP 90W - Boost Clock 1500/1740MHz',765,531);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-31','Cooling','100%imporved ventilation rate - 21% larger thermal Area - 35% higher TDP',766,531);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-31','OS','Pre-Loaded Windows 10 Home with Lifetime Validity',767,531);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-31','Wireless','Networking:  802.11AC (2 x 2) & Bluetooth® 5.0',768,531);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-32','Processor','Intel® Core™ i5-1035G1 (1.0 GHz base frequency, up to 3.6 GHz with Intel® Turbo Boost Technology, 6 MB L3 cache, 4 cores)',769,532);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-32','Memory','8 GB DDR4-2666 SDRAM (1 x 8 GB)',770,532);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-32','Storage','1 TB 5400 rpm SATA HDD',771,532);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-32','Display','39.6 cm (15.6") diagonal, HD (1366 x 768), anti-glare, 220 nits, 45% NTSC',772,532);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-32','Graphics','Integrated: Intel UHD Graphics',773,532);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-32','Wireless','Integrated 10/100/1000 GbE NIC Realtek RTL8821CE 802.11a/b/g/n/ac (1x1) Wi-Fi® Bluetooth® 4.2',774,532);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-33','Processor','Intel® Core™ i7-1065G7 (1.3 GHz base frequency, up to 3.9 GHz with Intel® Turbo Boost Technology, 8 MB L3 cache, 4 cores)',775,533);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-33','Memory','8 GB DDR4-2666 SDRAM (1 x 8 GB)',776,533);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-33','Storage','1 TB 5400 rpm SATA HDD',777,533);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-33','Display','39.6 cm (15.6") diagonal, HD (1366 x 768), anti-glare, 220 nits, 45% NTSC',778,533);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-33','Graphics','Intel® Iris® Plus Graphics',779,533);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-33','Wireless','Integrated 10/100/1000 GbE NIC Realtek RTL8821CE 802.11a/b/g/n/ac (1x1) Wi-Fi® Bluetooth® 4.2',780,533);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-33','system','Operating System: Windows 10 Home 64, English',781,533);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-34','Processor','Intel® Core™ i3-1115G4 (up to 4.1 GHz with Intel® Turbo Boost Technology, 6 MB L3 cache, 2 cores',782,534);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-34','Memory','4 GB DDR4-2666 MHz RAM (1 x 4 GB)',783,534);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-34','Storage','1 TB 5400 rpm SATA HDD',784,534);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-34','Display','39.6 cm (15.6") diagonal, HD (1366 x 768), micro-edge, anti-glare, 250 nits, 45% NTSC',785,534);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-34','Graphics','Intel® UHD Graphics',786,534);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-34','Wireless','Realtek RTL8821CE-M 802.11a/b/g/n/ac (1x1) Wi-Fi® and Bluetooth® 4.2 combo',787,534);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-34','system','Windows 10 Home 64',788,534);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-35','Processor','Intel® Core™ i7-1065G7 (1.3 GHz base frequency, up to 3.9 GHz base with Intel® Turbo Boost Technology, 8 MB cache, 4 cores)',789,535);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-35','Memory','16 GB DDR4 SDRAM',790,535);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-35','Storage','Internal drive: 512SSD Optical drive: None',791,535);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-35','Display','15.6” Full HD (1920 x 1080) TN, anti-glare',792,535);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-35','Graphics','Intel Iris Plus graphics',793,535);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-35','Wireless','Wi-Fi: Intel® Dual Band Wireless-AC 802.11ac  WiFi Bluetooth® 5.0',794,535);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-35','system','Operating System: DOS',795,535);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-36','Processor','11th Generation Intel® Core™ i7-1165G7 Processor (12MB Cache, 2.80 GHz up to 4.7 GHz),4 cores , 8 threads',796,536);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-36','Memory','8GB DDR4, 3200MHz',797,536);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-36','Storage','512 SSD Hard Drive',798,536);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-36','Display','15.6-inch FHD (1920 x 1080) Anti-glare LED Backlight Non-Touch Narrow Border WVA Display',799,536);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-36','Graphics','NVIDIA® GeForce® MX330 with 2GB GDDR5 graphics memory',800,536);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-36','Wireless','802.11ac 1x1 WiFi and Bluetooth 5.0',801,536);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-36','system','Ubuntu',802,536);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-37','Processor','Intel® Celeron® N4020 (1.1 GHz base frequency, up to 2.8 GHz burst frequency, 4 MB cache, 2 cores)',803,537);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-37','Memory','4 GB DDR4-2400 SDRAM (1 x 4 GB)',804,537);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-37','Storage','64 GB eMMC',805,537);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-37','Display','14" diagonal, HD (1366 x 768), micro-edge, BrightView, 220 nits, 45% NTSC',806,537);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-37','Graphics','Intel® UHD Graphics',807,537);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-37','Wireless','802.11ac (1x1) Wi-Fi® and Bluetooth® 4.2 combo',808,537);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-37','system','Windows 10 Home in S mode',809,537);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-38','Processor','Intel® Core™ i5-10210U Processor, 1.60 GHz (6M Cache, up to 3.9 GHz, # of Cores: 4)',810,538);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-38','Memory','Installed Memory: 8 GB RAM Memory Type: DDR4-2666',811,538);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-38','Storage','Storage Capacity: 1TB HDD',812,538);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-38','Display','Screen Size: 15.6-inch  Resolution: FHD (1920 x 1080)',813,538);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-38','Graphics','Graphics Processor: NVIDIA® GeForce® MX130 Graphics Video RAM: 2GB GDDR5',814,538);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-38','Wireless','Ethernet NIC: 10/100M Wi-Fi 802.11 b/g/n/ac Bluetooth® 4.1',815,538);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-38','system','Operating System: Free DOS',816,538);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-39','Processor','11th Generation Intel® Core™ i7-1165G7 Processor (12MB Cache, 2.80 GHz up to 4.7 GHz),4 cores , 8 threads',817,539);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-39','Memory','16GB DDR4, 3200MHz',818,539);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-39','Storage','512GB M.2 PCIe NVMe Solid State Drive  1TB Hard Drive',819,539);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-39','Display','15.6-inch FHD (1920 x 1080) Anti-glare LED Backlight Non-Touch Narrow Border WVA Display',820,539);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-39','Graphics','NVIDIA® GeForce® MX330 with 2GB GDDR5 graphics memory',821,539);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-39','Wireless','802.11ac (1x1) Wi-Fi® and Bluetooth® 4.2 combo',822,539);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-39','system','Windows 10 Professional',823,539);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-40','Processor','Processor Generation: 11th generation Processor Details: Intel® Core™ i7-1165G7 (up to 4.7 GHz with Intel® Turbo Boost Technology, 12 MB L3 cache, 4 cores)',824,540);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-40','Memory','RAM: 8 GB DDR4-2666 SDRAM (4 GB x 2)',825,540);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-40','Storage','Hard drive: 512 GB  PCIe® NVMe™ Value M.2 SSD',826,540);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-40','Display','Display: 15.6" FHD IPS eDP anti-glare slim, 250 nits, 45% NTSC Display Resolution: 1920 x 1080 Display Refresh Rate: 60 Hz',827,540);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-40','Graphics','Video graphics: NVIDIA GeForce MX450  Video graphics Memory: 2 GB DDR5 dedicated',828,540);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-40','Wireless','Intel® Dual Band Wireless-AC 9560 802.11a/b/g/n/ac (2x2) Wi-Fi® Bluetooth® 5',829,540);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-40','system','Operating System: Windows 11 Pro',830,540);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-41','Network','Supports 4G / 3G / 2G',831,541);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-41','Display','Dot Drop, HD + display, 6.53 '''' 720x1600 HD +',832,541);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-41','Platform','OS: Android 10',833,541);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-41','Body','164.9mm × 77.07mm × 9.0mmWeight: 196 g  SIM: Dual SIM (Nano-SIM, dual stand-by)',834,541);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-41','Memory','2 GB + 32 GB',835,541);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-41','Main Camera','13-megapixel rear camera Video: 1080P, 30FPS, 60FPS/720p, 30fps',836,541);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-41','Selfie Camera','5-megapixel selfie camera 1.12μm large pixel size',837,541);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-41','Communications','2 + 1 card slot design
Supports two SIM cards from two different companies; The two cards can connect to the 4G network at the same time
Supports two nano-SIM cards and micro-SD expansion, and either card can be set as the primary card.
Supports 4G / 3G / 2G',838,541);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-41','Battery','5,000 mAh (typical value) Supports charging capacity of 10 watts',839,541);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-42','Network','GSM / HSPA / LTE',840,542);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-42','Display','AMOLED, 450 nits (typ), 1100 nits (peak) 6.43 inches, 99.8 cm2 (~83.5% screen-to-body ratio)',841,542);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-42','Platform','Android 11, MIUI 12.5',842,542);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-42','Body','160.5 x 74.5 x 8.3 mm',843,542);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-42','Memory','microSDXC (dedicated slot)  128GB 6GB RAM UFS 2.2',844,542);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-42','Main Camera','64 MP, f/1.8, 26mm (wide), 1/1.97", 0.7µm, PDAF',845,542);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-42','Selfie Camera','13 MP, f/2.5, (wide), 1/3.06", 1.12µm',846,542);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-42','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',847,542);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-42','Battery','Type: Li-Po 5000 mAh, non-removable /Charging: Fast Charging 33W',848,542);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-43','Network','GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2',849,543);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-43','Display','LCD, 90Hz 6.5 inches, 102.0 cm2 (~83.4% screen-to-body ratio)',850,543);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-43','Platform','Android 11, MIUI 12.5',851,543);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-43','Body','162 x 75.5 x 8.9 mm',852,543);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-43','Memory','microSDXC (dedicated slot) 128GB 6GB RAM  eMMC 5.1',853,543);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-43','Main Camera','50 MP, f/1.8, (wide), PDAF',854,543);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-43','Selfie Camera','8 MP, f/2.0, (wide)',855,543);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-43','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',856,543);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-43','Battery','Li-Po 5000 mAh, non-removable  Charging: Fast charging 18W',857,543);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-44','Network','HSPA 21.1/5.76 Mbps, LTE Cat4 150/50 Mbps',858,544);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-44','Display','IPS LCD /6.6 inches, 105.2 cm2 (~83.2% screen-to-Body ratio)',859,544);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-44','Platform','Android 10 (Go edition) /Mediatek MT6761D Helio A20 (12 nm)',860,544);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-44','Body','165.4 x 76.4 x 8.8 mm/ 183 g',861,544);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-44','Memory','microSDXC (dedicated slot) /32GB 2GB RAM /eMMC 5.1',862,544);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-44','Main Camera','8 MP + QVGA',863,544);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-44','Selfie Camera','Single: 8 MP',864,544);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-44','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',865,544);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-44','Battery','Li-Po 5000 mAh, non-removable',866,544);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-45','Network','HSPA 42.2/5.76 Mbps, LTE-A',867,545);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-45','Display','Super AMOLED Plus, 90Hz',868,545);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-45','Platform','Android 11, One UI 3.0 /Qualcomm SM7125 Snapdragon 720G (8 nm)',869,545);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-45','Body','165 x 77.4 x 8.4 mm /203 g',870,545);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-45','Memory','microSDXC (dedicated slot) 128GB 8GB RAM/UFS 2.1',871,545);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-45','Main Camera','64 MP, f/1.8, 26mm (wide), 1/1.72", 0.8µm, PDAF, OIS',872,545);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-45','Selfie Camera','32 MP, f/2.2, 26mm (wide), 1/2.8", 0.8µm',873,545);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-45','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',874,545);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-45','Battery','Li-Ion 5000 mAh, non-removable',875,545);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-46','Network','HSPA 42.2/5.76 Mbps, LTE-A',876,546);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-46','Display','IPS LCD, 120Hz, HDR10, 450 nits (typ) / 6.67 inches, 107.4 cm2 (~84.6% screen-to-body ratio)',877,546);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-46','Platform','Android 11, MIUI 12 for POCO/Qualcomm Snapdragon 860 (7 nm)',878,546);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-46','Body','165.3 x 76.8 x 9.4 mm (6.51 x 3.02 x 0.37 in) / 215 g (7.58 oz)',879,546);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-46','Memory','microSDXC (uses shared SIM slot)/256GB 8GB RAM',880,546);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-46','Main Camera','48 MP, f/1.8, (wide), 1/2.0", 0.8µm, PDAF',881,546);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-46','Selfie Camera','20 MP, f/2.2, (wide), 1/3.4", 0.8µm',882,546);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-46','Communications','Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',883,546);
INSERT INTO dbo.ProductDetails(ITSIN,Title,Content,Id,ProductId) VALUES ('IT-CSV-46','Battery','Li-Po 5160 mAh, non-removable',884,546);

SET IDENTITY_INSERT dbo.ProductDetails OFF